name: Build and Deploy

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "adopt"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Extract Tag Name
        id: extract_tag
        run: echo "CLEAN_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create Release and Upload Artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/libs/*.jar
          tag: ${{ env.CLEAN_TAG }}
          name: ${{ env.CLEAN_TAG }}
          commit: ${{ github.sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
